name: Upload to Azure Storage

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Troubleshooting Secrets
        run: |
          echo "Checking Client ID..."
          if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then echo "MISSING: AZURE_CLIENT_ID"; fi
          echo "Checking Tenant ID..."
          if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then echo "MISSING: AZURE_TENANT_ID"; fi
          echo "Checking Subscription ID..."
          if [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then echo "MISSING: AZURE_SUBSCRIPTION_ID"; fi

      - name: Hard Debug Secrets
        run: |
          echo "Total Repository Secrets: $(env | grep -c 'AZURE_')" # This should be > 0
          [ -n "${{ secrets.AZURE_CLIENT_ID }}" ] && echo "Client ID Found" || echo "Client ID is MISSING"



      # - name: Check secret presence
      #   run: |
      #     if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then echo "AZURE_CLIENT_ID is EMPTY"; exit 1; fi
      #     if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then echo "AZURE_TENANT_ID is EMPTY"; exit 1; fi
      #     if [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then echo "AZURE_SUBSCRIPTION_ID is EMPTY"; exit 1; fi

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Storage Key from Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "blob-storage-credentials"
          secrets: "StorageKey"
        id: kv

      - name: Upload file to Blob Storage
        uses: azure/CLI@v2
        env:
          StorageKeyEnv: ${{ steps.kv.outputs.StorageKey }}
        with:
          inlineScript: |
            az storage blob upload \
              --account-name git1storage \
              --account-key "$StorageKeyEnv" \
              --container-name "github-uploads" \
              --file ./code.java \
              --name code.java

